package visitor;

//
// Generated by JTB 1.3.2
//

import java.util.HashMap;
import syntaxtree.*;
import java.util.*;
import symbol.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class BuildNode2 implements GJNoArguVisitor<String> {
    private HashMap<String, FlowGraph> flowGraphMap;
    private int currentNo;
    private HashMap<String, Integer> currentLabelMap;
    private FlowGraph currentFlowGraph;
    private boolean calling = false;

    public BuildNode2(HashMap<String, FlowGraph> fgm)
    {
        flowGraphMap = fgm;
    }
    //
    // Auto class visitors--probably don't need to be overridden.
    //
    public String visit(NodeList n) {
        String _ret=null;
        int _count=0;
        for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this);
            _count++;
        }
        return _ret;
    }

    public String visit(NodeListOptional n) {
        if ( n.present() ) {
            String _ret=null;
            int _count=0;
            for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
                e.nextElement().accept(this);
                _count++;
            }
            return _ret;
        }
        else
            return null;
    }

    public String visit(NodeOptional n) {
        if ( n.present() )
            return n.node.accept(this);
        else
            return null;
    }

    public String visit(NodeSequence n) {
        String _ret=null;
        int _count=0;
        for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this);
            _count++;
        }
        return _ret;
    }

    public String visit(NodeToken n) { return null; }

    //
    // User-generated visitor methods below
    //

    /**
     * f0 -> "MAIN"
     * f1 -> StmtList()
     * f2 -> "END"
     * f3 -> ( Procedure() )*
     * f4 -> <EOF>
     */
    public String visit(Goal n) {
        currentFlowGraph = flowGraphMap.get("MAIN");
        currentLabelMap = currentFlowGraph.mLabel;
        currentNo = 0;
        currentFlowGraph.addEdge(currentNo, currentNo+1);
        currentNo++;
        String _ret=null;
        n.f1.accept(this);
        n.f3.accept(this);
        return _ret;
    }

    /**
     * f0 -> ( ( Label() )? Stmt() )*
     */
    public String visit(StmtList n) {
        String _ret=null;
        n.f0.accept(this);
        return _ret;
    }

    /**
     * f0 -> Label()
     * f1 -> "["
     * f2 -> IntegerLiteral()
     * f3 -> "]"
     * f4 -> StmtExp()
     */
    public String visit(Procedure n) {
        String _ret=null;
        currentNo = 0;
        currentFlowGraph = flowGraphMap.get(n.f0.accept(this));
        currentLabelMap = currentFlowGraph.mLabel;
        currentFlowGraph.addEdge(currentNo, currentNo+1);
        currentNo++;
        n.f2.accept(this);
        n.f4.accept(this);
        return _ret;
    }

    /**
     * f0 -> NoOpStmt()
     *       | ErrorStmt()
     *       | CJumpStmt()
     *       | JumpStmt()
     *       | HStoreStmt()
     *       | HLoadStmt()
     *       | MoveStmt()
     *       | PrintStmt()
     */
    public String visit(Stmt n) {
        String _ret=null;
        n.f0.accept(this);
        currentNo++;
        return _ret;
    }

    /**
     * f0 -> "NOOP"
     */
    public String visit(NoOpStmt n) {
        String _ret=null;
        currentFlowGraph.addEdge(currentNo, currentNo+1);
        n.f0.accept(this);
        return _ret;
    }

    /**
     * f0 -> "ERROR"
     */
    public String visit(ErrorStmt n) {
        String _ret=null;
        currentFlowGraph.addEdge(currentNo, currentNo+1);
        n.f0.accept(this);
        return _ret;
    }

    /**
     * f0 -> "CJUMP"
     * f1 -> Temp()
     * f2 -> Label()
     */
    public String visit(CJumpStmt n) {
        String _ret=null;
        FlowBlock flowBlock;
        currentFlowGraph.addEdge(currentNo, currentNo+1);
        flowBlock = currentFlowGraph.getBlock(currentNo);
        String l;
        n.f0.accept(this);
        flowBlock.right.add(Integer.valueOf(n.f1.accept(this)));
        l = n.f2.accept(this);
        currentFlowGraph.addEdge(currentNo, currentLabelMap.get(l));
        return _ret;
    }

    /**
     * f0 -> "JUMP"
     * f1 -> Label()
     */
    public String visit(JumpStmt n) {
        String _ret=null;
        String l;
        n.f0.accept(this);
        l = n.f1.accept(this);
        currentFlowGraph.addEdge(currentNo, currentLabelMap.get(l));
        return _ret;
    }

    /**
     * f0 -> "HSTORE"
     * f1 -> Temp()
     * f2 -> IntegerLiteral()
     * f3 -> Temp()
     */
    public String visit(HStoreStmt n) {
        String _ret=null;
        FlowBlock flowBlock;
        currentFlowGraph.addEdge(currentNo, currentNo+1);
        flowBlock = currentFlowGraph.getBlock(currentNo);
        flowBlock.right.add(Integer.valueOf(n.f1.accept(this)));
        n.f2.accept(this);
        flowBlock.right.add(Integer.valueOf(n.f3.accept(this)));
        return _ret;
    }

    /**
     * f0 -> "HLOAD"
     * f1 -> Temp()
     * f2 -> Temp()
     * f3 -> IntegerLiteral()
     */
    public String visit(HLoadStmt n) {
        String _ret=null;
        FlowBlock flowBlock;
        currentFlowGraph.addEdge(currentNo, currentNo+1);
        flowBlock = currentFlowGraph.getBlock(currentNo);
        flowBlock.left.add(Integer.valueOf(n.f1.accept(this)));
        flowBlock.right.add(Integer.valueOf(n.f2.accept(this)));
        n.f3.accept(this);
        return _ret;
    }

    /**
     * f0 -> "MOVE"
     * f1 -> Temp()
     * f2 -> Exp()
     */
    public String visit(MoveStmt n) {
        String _ret=null;
        FlowBlock flowBlock;
        currentFlowGraph.addEdge(currentNo, currentNo+1);
        flowBlock = currentFlowGraph.getBlock(currentNo);
        flowBlock.left.add(Integer.valueOf(n.f1.accept(this)));
        n.f2.accept(this);
        return _ret;
    }

    /**
     * f0 -> "PRINT"
     * f1 -> SimpleExp()
     */
    public String visit(PrintStmt n) {
        String _ret=null;
        currentFlowGraph.addEdge(currentNo, currentNo+1);
        n.f0.accept(this);
        n.f1.accept(this);
        return _ret;
    }

    /**
     * f0 -> Call()
     *       | HAllocate()
     *       | BinOp()
     *       | SimpleExp()
     */
    public String visit(Exp n) {
        String _ret=null;
        n.f0.accept(this);
        return _ret;
    }

    /**
     * f0 -> "BEGIN"
     * f1 -> StmtList()
     * f2 -> "RETURN"
     * f3 -> SimpleExp()
     * f4 -> "END"
     */
    public String visit(StmtExp n) {
        String _ret=null;
        n.f1.accept(this);
        n.f3.accept(this);
        currentFlowGraph.addEdge(currentNo, currentNo+1);
        return _ret;
    }

    /**
     * f0 -> "CALL"
     * f1 -> SimpleExp()
     * f2 -> "("
     * f3 -> ( Temp() )*
     * f4 -> ")"
     */
    public String visit(Call n) {
        String _ret=null;
        n.f1.accept(this);
        calling = true;
        n.f3.accept(this);
        calling = false;
        return _ret;
    }

    /**
     * f0 -> "HALLOCATE"
     * f1 -> SimpleExp()
     */
    public String visit(HAllocate n) {
        String _ret=null;
        n.f0.accept(this);
        n.f1.accept(this);
        return _ret;
    }

    /**
     * f0 -> Operator()
     * f1 -> Temp()
     * f2 -> SimpleExp()
     */
    public String visit(BinOp n) {
        String _ret=null;
        FlowBlock flowBlock;
        flowBlock = currentFlowGraph.getBlock(currentNo);
        n.f0.accept(this);
        flowBlock.right.add(Integer.valueOf(n.f1.accept(this)));
        n.f2.accept(this);
        return _ret;
    }

    /**
     * f0 -> "LT"
     *       | "PLUS"
     *       | "MINUS"
     *       | "TIMES"
     */
    public String visit(Operator n) {
        String _ret=null;
        n.f0.accept(this);
        return _ret;
    }

    /**
     * f0 -> Temp()
     *       | IntegerLiteral()
     *       | Label()
     */
    public String visit(SimpleExp n) {
        String _ret=null;
        String tmp = n.f0.accept(this);
        if (n.f0.which == 0)
        {
            // is Temp
            FlowBlock flowBlock = currentFlowGraph.getBlock(currentNo);
            flowBlock.right.add(Integer.valueOf(tmp));
        }
        return _ret;
    }

    /**
     * f0 -> "TEMP"
     * f1 -> IntegerLiteral()
     */
    public String visit(Temp n) {
        String _ret=null;
        n.f0.accept(this);
        _ret = n.f1.accept(this);
        if (calling)
        {
            FlowBlock flowBlock = currentFlowGraph.getBlock(currentNo);
            flowBlock.right.add(Integer.valueOf(_ret));
        }
        return _ret;
    }

    /**
     * f0 -> <INTEGER_LITERAL>
     */
    public String visit(IntegerLiteral n) {
        String _ret=null;
        _ret = n.f0.toString();
        n.f0.accept(this);
        return _ret;
    }

    /**
     * f0 -> <IDENTIFIER>
     */
    public String visit(Label n) {
        String _ret=null;
        _ret = n.f0.toString();
        n.f0.accept(this);
        return _ret;
    }

}